name: Deploy Backend to Cloud Run

on:
    push:
        branches: [main]
    workflow_dispatch:

env:
    PROJECT_ID: nutrifit-459709
    SERVICE_NAME: nutri-fit-back
    REGION: europe-west1

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Google Auth
              id: auth
              uses: google-github-actions/auth@v1
              with:
                  credentials_json: ${{ secrets.GCP_SA_KEY }}
                  project_id: ${{ env.PROJECT_ID }}

            - name: Set up Cloud SDK
              uses: google-github-actions/setup-gcloud@v1
              with:
                  project_id: ${{ env.PROJECT_ID }}

            - name: Authorize Docker push
              run: gcloud auth configure-docker

            - name: Build and Push Backend Container
              run: |
                  docker build -t gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }} .
                  docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }}

            - name: Deploy Backend to Cloud Run
              run: |
                  gcloud run deploy ${{ env.SERVICE_NAME }} \
                    --image gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }} \
                    --region ${{ env.REGION }} \
                    --platform managed \
                    --allow-unauthenticated \
                    --set-env-vars "TOKEN_SECRET=${{ secrets.TOKEN_SECRET }}" \
                    --set-env-vars "DB_URL=${{ secrets.DB_URL }}" \
                    --set-env-vars "PROJECT_ID=${{ secrets.PROJECT_ID }}" \
                    --set-env-vars "PRIVATE_KEY_ID=${{ secrets.PRIVATE_KEY_ID }}" \
                    --set-env-vars "PRIVATE_KEY=${{ secrets.PRIVATE_KEY }}" \
                    --set-env-vars "CLIENT_EMAIL=${{ secrets.CLIENT_EMAIL }}" \
                    --set-env-vars "CLIENT_ID=${{ secrets.CLIENT_ID }}" \
                    --set-env-vars "CLIENT_X509_CERT_URL=${{ secrets.CLIENT_X509_CERT_URL }}"
